version: "3.7"
services:
  gateway:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker/development/nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./api:/app